### ISSUE TITLE
Add a Software License

### ISSUE THREAD

**Issue by benjic** [dstoeg/Uml2CodeTool#1]
As a contributor it would be beneficial to have a license for the project before submitting a contribution. If the project plans to be developed as open source will it contain a license?

**Comment by dstoeg** [comment]
We have discussed the issue, but since we don't have too much experience in software licensing, we didn't make any decisions yet. Any suggestions?

**Comment by dstoeg** [comment]
I did some research, and i think i prefer either GPLv3 or MIT license. What do you think?

**Comment by benjic** [comment]
Awesome, thanks for the quick turnaround! 

I think the choice depends on the long term usage of the software. MIT limits your liability and allows the software to be used in any case which is very liberating for consumers. GPL guarantees the freedom of the software/program by preventing others from using the software in non free software. This can be restrictive for consumers who would like to use the software in their project but don't want to release their software as GPL.
