### ISSUE TITLE
Implement selecting classes in Canvas

### ISSUE THREAD

**Issue by dstoeg** [dstoeg/Uml2CodeTool#20]

**Comment by dstoeg** [comment]
User can click a class in the canvas.

Then attributes are loaded in the class info bar.

User has to be able to update the class using the update button.

User has to be able to delete classes from the canvas and the app logic

**Comment by mkinsey** [comment]
To do this we need to store some position information about each class. Should we do this in uInheritable or try to store it within the canvas? I would be happy to work on it

**Comment by dstoeg** [comment]
I think we shouldn't put it in uInheritable. I guess we could create a new class, which stores a table (2d array), where the entries are the names of the uInheritable objects.
